# Generated by Django 6.0.3 on 2026-03-17 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('event_name', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Contact number must be between 9-15 digits, optionally starting with +', regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
