spring.application.name=inventory
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/productdb

spring.security.user.name=admin
spring.security.user.password=password

logging.level.org.springframework.security=INFO
